### ISSUE TITLE
Using SSL in Elasticsearch Cross Cluster settings

### ISSUE THREAD

**Issue by dragan979** [floragunncom/search-guard-ssl#101]
I used this guide https://gryzli.info/2018/12/01/elasticsearchelk-stack-security-howto/ to encrypt Elasticsearch and it works fine, but it seems it Can't be used in Cross-cluster search settings (it asks only for IP and port number)

**Comment by floragunncom** [comment]
Cross cluster search is fully supported by Search Guard. Please refer to https://docs.search-guard.com/latest/cross-cluster-tribe#cross-cluster-search-support
