### ISSUE TITLE
Tribe nodes not getting pass values in elasticsearch.yml config file

### ISSUE THREAD

**Issue by TinLe** [floragunncom/search-guard-ssl#12]
This is because Elastic is restricting what is being passed through.  ES v2.2.0

https://github.com/elastic/elasticsearch/pull/16893

From debugging, I see that nothing from "searchguard.*" properties is making it through when setting up tribes.   This is needed of course as the clusters the tribe is talking to is using transport over SSL.

Ugh.  My patching didn't help.   Need to somehow get the properties from elasticsearch config file through tribe blocks.

For now, my workaround is to have a static init that give all the defaults I needed from the config.  Of course that meant re-compiling new jar each time it changes :-(

**Comment by floragunncom** [comment]
see https://github.com/floragunncom/search-guard-ssl/blob/216bb6190bcd714adc2caaf06c0fe7438826f63e/src/main/java/com/floragunn/searchguard/ssl/SearchGuardSSLModule.java and https://github.com/floragunncom/search-guard-ssl/blob/master/src/main/java/com/floragunn/searchguard/ssl/SearchGuardSSLSettingsFilter.java

All SG properties will be filtered for security reasons

**Comment by TinLe** [comment]
The filter does not seem to work.   I compiled from HEAD last night and in debug mode, I can see that nothing for searchguard.* gets through when running in tribe mode.

Probably a bug on ES filtering side.

**Comment by floragunncom** [comment]
When nothing comes through the filter _DID_ work

**Comment by TinLe** [comment]
I guess I am confused.   None of the searchguard.* properties get passed through to sg plugin, and that is working as designed?

How so?

**Comment by floragunncom** [comment]
sorry got you wrong - i mean when you call /_nodes/settings via http/rest settings are filtered out. Installing SG on a tribe node is currently untested, so would be great to figure out whats wrong here.

**Comment by TinLe** [comment]
I think it's a bug on ES side.   In tribe mode, they are not passing through most properties in ES config file.   Unfortunately, it's buggy at moment.   They are passing through things that should not be, and blocking others that should be.

The long term fix for SG is to add to the init function a check in config dir for SG's own config file.  E.g. check in $CONFIG_DIR for search-guard-ssl.yml, and if it is there read it (values there override everything else).   Users still have option of putting SG properties in ES config.

**Comment by floragunncom** [comment]
will investigate

**Comment by TinLe** [comment]
Figured it out!

If I copied searchguard.* properties and put the same under each tribe downstream cluster, then they get passed through.... to tribe (wtf!).   Anyway, doing that allow SG to work.

E.g.

tribe.downstream1.searchguard.ssl.etc

Will pass through searchguard.ssl.etc

**Comment by TinLe** [comment]
Closing as it is not an SG bug, but ES one.   I'll document how to setup ES tribe with SG on my blog.

**Comment by floragunncom** [comment]
thx, can you pls post the link here so we can refer to it (and include them in the docs)?

**Comment by TinLe** [comment]
OK.   I've posted blog on how to get SG-SSL working with ES 2.x and with security policy manager turn on.

http://blog.tinle.org/?p=505


I'll post how to use tribe with SG-SSL as a followup.   I am waiting for time to test ES 2.2.1 as that supposedly fixed the tribe node bug in ES.   If that is the case, it will change my how-to post, so I want to test first.

**Comment by floragunncom** [comment]
thats great, thx a lot
