### ISSUE TITLE
version information wrong for 2.2.0.6

### ISSUE THREAD

**Issue by Elemecca** [floragunncom/search-guard-ssl#14]
In the [`plugin-descriptor.properties` file for version 2.2.0.6](https://github.com/floragunncom/search-guard-ssl/blob/v2.2.0.6/plugin-descriptor.properties#L6), the version property is still set to 2.2.0.5. That's causing issues with my deployment automation, which always thinks the plugin is out of date and so re-installs it on every run.

I don't really know the right approach to fix this, since Maven release artifacts are supposed to be immutable. Maybe just release 2.2.0.7 with no changes except fixing the errant version number?

Separately, you may want to make Maven generate the `plugin-descriptor.properties` file as part of the build so that the version always matches the one in the POM, which will make it so using the Maven release plugin will just work.

**Comment by floragunncom** [comment]
thx, will fix this
