### ISSUE TITLE
Truststore settings not sufficient in more complex cases

### ISSUE THREAD

**Issue by jammann** [floragunncom/search-guard-ssl#16]
I started to use SG SSL 2.2.0.6 with ES 2.2.0. Everything works fine with very simple keystores (one cert/key, one cacert, all certs of the machines in the cluster signed by the same CA).

In Test and Production we have a more complex setup, where the current implementation seems to have some shortcomings.

We have separate keystores (with just 1 key/cert and the CA cert) and truststores (with many CA certs, but no keys, hence no need to encrypt). There are a few issues
- our truststore doesn't have a password, but SG SSL does not allow a truststore without password. Either it takes the default from the code ("changeit") if I don't specify the parameter, or we get a NPE when setting it to NULL (during copying of the settings), or we get a "keystore has been tampered with" if we set it to an empty string ("")
- we'd want all CA certs in that keystore to be accepted as valid CA certs, but if we don't specify the truststore_alias parameter, SG SSL falls back to using the keystore_alias. We'd like to have an option to simply say "accept certs from all CA certs in the truststore)

I'd be happy to cooperating in implementing and/or testing these improvements

**Comment by floragunncom** [comment]
good catch, agreed.

Do you like to submit a PR or want me to fix this?

**Comment by jammann** [comment]
I'm struggling a bit to get my build environment going. It would probably be better if you fix it yourself. I don't feel too comfortable yet to submit a PR :-)

**Comment by floragunncom** [comment]
how do you generate you truststore without a password?

**Comment by jammann** [comment]
Actually my wording was bad. A JKS always has a store password (AFAIK), but it is not necessary to specify it when using the JKS as pure truststore (access only the certificate, no private keys). We normally use something like the following to generate our truststores

```
keytool -importcert -trustcacerts -noprompt -alias $_certLabel -file "$TEMPDIR/trustcerts/$_certLabel.pem" -keystore $TEMPDIR/trustcerts/truststore.jks -storepass password
```

In Java code, we access it like

```
KeyStore trustStore = KeyStore.getInstance("JKS");
trustStore.load(
	new FileInputStream(trustStorePath),
		trustStorePassword == null ? null : trustStorePassword.toCharArray());

TrustManagerFactory trustManagerFactory = TrustManagerFactory
					.getInstance(TrustManagerFactory.getDefaultAlgorithm());
trustManagerFactory.init(trustStore);
```

This works for us. But you're right, in fact the JKS still does have a password - I just had forgotten about this :-P So this is probably not a real issue.

**Comment by floragunncom** [comment]
can you check if this build fixes your problem? https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-ssl/2.3.1.9-SNAPSHOT/search-guard-ssl-2.3.1.9-20160409.191624-1.zip (its build for ES 2.3.1)

**Comment by floragunncom** [comment]
can you pls verify that its fixed?

**Comment by jammann** [comment]
Sorry, was away and terribly busy. Finally got around integrating and testing with ES 2.3.2 and Searchguard 2.3.2.9

Can confirm that all my required use cases now work perfectly
* using same JKS for keystore and truststore, select one single CA as trust
* using same JKS for keystore and truststore, allow all CAs as trust
* using different JKS for keystore and truststore, select one single CA as trust
* using different JKS for keystore and truststore, allow all CAs as trust

Thanks a lot for this feature!
