### ISSUE TITLE
version 2.3.x and upgrades in general

### ISSUE THREAD

**Issue by tomryanx** [floragunncom/search-guard-ssl#17]
Would it be possible to give an approximate ETA on a 2.3.x version of search-guard-ssl?  I'm dead keen to try out Graph but obviously can't upgrade ES at this point without losing SSL between nodes.

I'm also curious about what, if anything, can be done to assist with closer tracking of ES versions in general.

**Comment by floragunncom** [comment]
released yesterday (2.3.1.8)

**Comment by floragunncom** [comment]
what do you mean with "I'm also curious about what, if anything, can be done to assist with closer tracking of ES versions in general."
