### ISSUE TITLE
Need a version compatible with ES 2.3.2

### ISSUE THREAD

**Issue by the-james-burton** [floragunncom/search-guard-ssl#19]
Sorry to bother with this trivial issue, but using ES 2.3.1 I recently hit ES bug [#17483](https://github.com/elastic/elasticsearch/issues/17483), so I was forced to upgrade to 2.3.2. 

I know your software says 2.3.1, but I tried it on 2.3.2 anyway...

```ERROR: Plugin [search-guard-ssl] is incompatible with Elasticsearch [2.3.2]. Was designed for version [2.3.1]```

I'm surprised that ES plugins are so tight on compatibility, even the patch version number? Anyway, I'm looking forward to 2.3.2 compatibility!

Regards, James

**Comment by floragunncom** [comment]
fixed, we released today search-guard-ssl and search-guard compatible with ES 2.3.2

<pre>
./plugin install com.floragunn/search-guard-ssl/2.3.2.9
./plugin install com.floragunn/search-guard-2/2.3.2.0-beta2
</pre>

**Comment by the-james-burton** [comment]
Awesome! Thank you very much!
