### ISSUE TITLE
Automatically build releases

### ISSUE THREAD

**Issue by t0xicCode** [floragunncom/search-guard-ssl#2]
Would it be feasible to setup travis-ci (or some other continuous delivery platform) to automatically build a new release when a new point release of elasticsearch is made?

**Comment by floragunncom** [comment]
thats a good idea, thank. Will do this.

**Comment by floragunncom** [comment]
thats not so easy because we need to sign all artifacts with pgp so that we can push it to maven central. A automatic release would imply that we store the secret pgp key on a server, thats not a good idea :-)

maybe we can set up a private build server, we are investigating that ...

**Comment by vroomvroomvroom** [comment]
still help wanted?

**Comment by floragunncom** [comment]
yes

**Comment by vroomvroomvroom** [comment]
let me know when we can chat about it

**Comment by digitalkaoz** [comment]
@floragunncom travis lets you store sensitive data in a `vault` https://docs.travis-ci.com/user/encryption-keys/
