### ISSUE TITLE
TLS versions and SSL cipher suites.

### ISSUE THREAD

**Issue by dashawn888** [floragunncom/search-guard-ssl#21]
Please add the choice of TLS versions and SSL cipher suites.

See https://groups.google.com/d/topic/search-guard/1BX9xyiAXII/discussion for reference.

Thanks,

Shawn

**Comment by floragunncom** [comment]
does https://github.com/floragunncom/search-guard-ssl/commit/08487b825adf65a5559bad163885f35d07311fac will fit you needs?

**Comment by dashawn888** [comment]
Thanks. This gives me what I was looking for. =)
