### ISSUE TITLE
Generating Client/Node certificates and Using Domain Certificate for HTTPS Endpoint

### ISSUE THREAD

**Issue by iboware** [floragunncom/search-guard-ssl#22]
It would be nice to have a guide to generate client and node SSL certificates with an existing certificate. I have a Wildcard SSL Certificate  but I could not manage to use it yet. I am trying and searching for this since days.

**Comment by floragunncom** [comment]
What have you tried so far and which kind of error messages you got?

**Comment by iboware** [comment]
Hi, my knowledge about SSL certificates and signing etc. was really very little but I have learned a lot in  a few days and I understood that I cannot sign a generated client or node certificate with a domain validation certificate. So I decided to use my wildcard domain certificate with the HTTP/REST and Kibana endpoints while using self generated root, client and node certificates for the transport. I generated that root and node certificates with the script provided by you just modifying required parameters like domain name etc. I was successful with that approach till one point, HTTPS is working great but then I noticed my nodes won't see each other.

When I restart both nodes I get this error from the second node, while the first one works alone as a cluster:
```
Exception in thread "main" MasterNotDiscoveredException[null]
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$5.onTimeout(TransportMasterNodeAction.java:226)
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:236)
	at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(InternalClusterService.java:804)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

This is the config of one of my nodes. The other is also identical except node name and key/truststore file configurations.
```
cluster.name: Alpha
node.name: Vulcan
network.host: 0.0.0.0
discovery.zen.ping.unicast.hosts: ["elastic1.mydomain.com", "elastic2.mydomain.com"]
#discovery.zen.minimum_master_nodes: 2
#Azure Configuration
#.....
#Search-Guard
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: /usr/share/elasticsearch/config/web-keystore.jks
searchguard.ssl.http.keystore_password: '********'
searchguard.ssl.http.truststore_filepath: /usr/share/elasticsearch/config/web-truststore.jks
searchguard.ssl.http.truststore_password: '*******'
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_filepath: /usr/share/elasticsearch/config/elastic1-keystore.jks
searchguard.ssl.transport.keystore_password: '*********'
searchguard.ssl.transport.truststore_filepath: /usr/share/elasticsearch/config/truststore.jks
searchguard.ssl.transport.truststore_password: '*********'
searchguard.ssl.transport.enforce_hostname_verification: true
searchguard.authcz.admin_dn:
  - "CN=admin,OU=client,O=client,L=Test,C=DE"
searchguard.ssl.transport.enable_openssl_if_available: true
searchguard.ssl.http.enable_openssl_if_available: true
```

**Comment by iboware** [comment]
I think I have an idea about why this happens. Could it be because of my vm's host name? When I ping it, i get myserver.westeurope.cloudapp.azure.com, because I used a CNAME record. My node certificate is for elastic1.myserver.com and elastic2.myserver.com I tried to set hostname validation to false, but it does not work.

`searchguard.ssl.transport.resolve_hostname: false`

**Comment by floragunncom** [comment]
try ``searchguard.ssl.transport.enforce_hostname_verification: false``

**Comment by floragunncom** [comment]
``searchguard.ssl.transport.resolve_hostname: true`` (which is the default) will trigger a reverse dns lookup whereas ``searchguard.ssl.transport.resolve_hostname: false`` does not. So settings this to ``true`` should resolve the hostname to you CNAME entry. ``searchguard.ssl.transport.resolve_hostname`` is only respected if ``searchguard.ssl.transport.enforce_hostname_verification ``is `true``.

**Comment by iboware** [comment]
As I said previously it works if I disable enforce_hostname_verification it works flawlessly. In the morning I updated my domain name with A Records pointing to static ip addresses of my hosts then i tried all possible combinations. Nothing worked actually. I am not sure if my es cluster is going to be vulnerable against man in the middle attacks, if this setting is disabled. I just wonder why is this validation failing. Is there any way to debug it, so I can fix this problem?

**Comment by floragunncom** [comment]
Pls. try the following:

* Disable OpenSSL support by setting ``searchguard.ssl.transport.enable_openssl_if_available: false``
* Enable SSL debug mode on JVM level ``export ES_JAVA_OPTS="-Djavax.net.debug=ssl"`` (maybe you have to add this in start scripts depending on what kind of elasticsearch package you have installed)

Beware: This produce a huge amount of output but should contain information about whats going wrong.

Can you please also post the following infos about your environment:
* Search Guard and Elasticsearch version
* JVM version and operating system version
* OpenSSL Version (if you use openssl) 

We strongly recommend Oracle Java 8 as the JVM cause OpenJDK and/or Java 1.7 are knwon for strange SSL related behaviour.

**Comment by floragunncom** [comment]
You may also look into [network configuration](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html) of elasticsearch, especially on the ``network.publish_host`` setting. Maybe the node advertises themselves with an awkward hostname.

Can you also share your Azure config?

**Comment by iboware** [comment]
I will try your suggestions tonight, but before that I want to inform you about my environment. It actually works on a docker container which I extended using by the official docker image. You can check my deployment configuration here:
https://github.com/iboware/elasticsearch-docker/blob/master/Dockerfile
**Runtime Environment:**
ElasticSearch 2.3.3
OpenSSL 1.0.1t
com.floragunn/search-guard-ssl/2.3.3.11
com.floragunn/search-guard-2/2.3.3.0-rc1
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-1~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
Debian 8 (jessie)

Btw. I didn't get what would you like to know about my azure configuration or which configuration. Can you be a bit specific about it?
Thanks

**Comment by floragunncom** [comment]
Please update to OpenSSL 1.0.2 cause hostname verification may not work with 1.0.1. You should also consider to use Oracle Java 8 instead of Open JDK 8. Pls do also upgrade netty native from 1.1.33.Fork15 to 1.1.33.Fork17 and libapr to 1.5.2.

Regarding Azure i meant whats beneath:
```
#Azure Configuration
#.....
```

**Comment by iboware** [comment]
Ah ok, actually this part has no relation with that problem. It is just azure storage configuration for snapshot/restore like this:
cloud.azure.storage.arbitaryname.account: 'somestorageaccount'
cloud.azure.storage.arbitaryname.key: 'storageaccountkey'

I will try what you have suggested me tonight and I will return the results. Thanks.

**Comment by iboware** [comment]
I updated every library as you said but it didn't work. In the end I tried the easiest thing, which I wasn't expecting it to work, but it worked! :) 
`network.publish_host: elastic1.mydomain.com`
Maybe you can add those small but tricky details into wiki page including OpenSSL 1.0.2, apr1.5.2, netty 1.1.33.Fork17 etc. because it was referring to older versions.
Thank you very much for your help :+1:
