### ISSUE TITLE
SearchGuardKeyStore logging Elasticsearch settings

### ISSUE THREAD

**Issue by twatson83** [floragunncom/search-guard-ssl#23]
SearchGuardKeyStore is writing all ElasticSearch settings to log.  The settings can contain passwords so I believe this is a security issue.

`[2016-06-14 09:02:37,059][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Effective settings:

client.type=node
cluster.name=xxxx
config.ignore_system_properties=true
http.cors.allow-credentials=true
http.cors.allow-origin=/.*/
http.cors.enabled=true
name=Impossible Man
searchguard.authcz.admin_dn.0=CN=xxxx, OU=xxxx, O=xxxx, L=xxx, ST=xxxx, C=xxx
searchguard.ssl.http.enabled=true
searchguard.ssl.http.keystore_alias=xxxx
searchguard.ssl.http.keystore_filepath=node.jks
searchguard.ssl.http.keystore_password=secret
searchguard.ssl.http.truststore_filepath=truststore.jks
searchguard.ssl.http.truststore_password=secret
searchguard.ssl.transport.enforce_hostname_verification=false
searchguard.ssl.transport.keystore_alias=node
searchguard.ssl.transport.keystore_filepath=node.jks
searchguard.ssl.transport.keystore_password=secret
searchguard.ssl.transport.truststore_filepath=truststore.jks
searchguard.ssl.transport.truststore_password=secret
`

**Comment by floragunncom** [comment]
will fix this, thx
