### ISSUE TITLE
 No user found in this UnicastPingRequest for action internal:discovery/zen/unicast and transport type netty.

### ISSUE THREAD

**Issue by djzort** [floragunncom/search-guard-ssl#27]
I am trying to get two nodes to talk to eachother wish search-guard-ssl.

On one node i get this error:
`[2016-06-27 16:26:51,613][ERROR][com.floragunn.searchguard.transport.SearchGuardTransportService] No user found in this UnicastPingRequest for action internal:discovery/zen/unicast and transport type netty. If you see this error related when you use sgadmin make sure you connect with a client (and not with a node) certificate.`

On the other i get:
`[2016-06-27 16:29:21,172][WARN ][discovery.zen            ] [xxxxxxxxxxx01] failed to validate incoming join request from node [{xxxxxxxxxxx02}{yZAXYebuQBeYGlmfTKOIvw}{10.116.76.77}{xxxxxxxxxxx02.ourdomain.local/10.116.76.77:19300}{data=false, city=local, master=true}]`

```
java -version
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
[root@hbasemgmt01.test1 search-guard]# 
```
```

rpm -qi elasticsearch
Name        : elasticsearch                Relocations: /usr 
Version     : 2.3.3                             Vendor: (none)
Release     : 1                             Build Date: Wed 18 May 2016 01:49:40 AEST
Install Date: Fri 24 Jun 2016 12:27:10 AEST      Build Host: vagrant-ubuntu-trusty-64
Group       : Application/Internet          Source RPM: elasticsearch-2.3.3-1.src.rpm
Size        : 30789310                         License: (c) 2009
Signature   : RSA/SHA1, Wed 18 May 2016 01:49:42 AEST, Key ID d27d666cd88e42b4
Packager    : Elasticsearch
Summary     : Distribution: RPM
Description :
Elasticsearch is a distributed RESTful search engine built for the cloud. Reference documentation can be found at https://www.elastic.co/guide/en/elasticsearch/reference/current/index.html and the 'Elasticsearch: The Definitive Guide' book can be found at https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html
```

**Comment by floragunncom** [comment]
Can you pls. share your elasticsearch.yml and tell us which Search Guard SSL version you are using. Besides this it looked like that you have also installed Search Guard (and not only Search Guard SSL)

**Comment by djzort** [comment]
Yes I have installed both, and am trying to slowly work through the steps to make them work. Here is the two plug in files:

search-guard-2-2.3.3.1.zip
search-guard-ssl-2.3.3.13.zip

I have just removed the search-guard-2 for now, and things look better now.

Thanks for quick response and helpful hint
