### ISSUE TITLE
how can i yum install elasticsearch 2.3.4

### ISSUE THREAD

**Issue by bujarmetaj2016** [floragunncom/search-guard-ssl#32]
Hi 
how can I install elasticsearch 2.3.4 ?
[elasticsearch]
name=Elasticsearch repository for 2.x packages
baseurl=http://packages.elastic.co/elasticsearch/2.x/centos
gpgcheck=1
gpgkey=http://packages.elastic.co/GPG-KEY-elasticsearch
enabled=1
Many thanks
B

**Comment by floragunncom** [comment]
Pls. ask purely (non Search Guard) related elasticsearch questions here: https://discuss.elastic.co
