### ISSUE TITLE
Server certificate being emitted twice, preventing host verification

### ISSUE THREAD

**Issue by chmarr** [floragunncom/search-guard-ssl#36]
Both the http and transport layers are emitting the server certificate part of the certificate chain twice. Eg, this output from using `openssl -s_client`:

```
---
Certificate chain
 0 s:/C=US/O=ExampleCo/OU=Example Systems/CN=test1.example.com
   i:/C=US/O= ExampleCo/OU= Example Systems/CN= ExampleCo Intermediate Authority
 1 s:/C=US/O= ExampleCo/OU= Example Systems/CN= ExampleCo Intermediate Authority
   i:/C=US/O= ExampleCo/OU= Example Systems/CN= ExampleCo Root Authority
 2 s:/C=US/O= ExampleCo/OU= Example Systems/CN=test1.example.com
   i:/C=US/O= ExampleCo/OU= Example Systems/CN= ExampleCo Intermediate Authority
---
```

This stops a slew of tools working (such as python elasticsearch client, or python requests) when I try to turn on host verification. The culprit is two instances in SSLCertificateHelper.java at line 66, and 79:

```
            Certificate[] certs = ks.getCertificateChain(alias);
            if(certs != null && certs.length > 0) {
                trustedCerts.addAll(Arrays.asList(certs));
            }
            Certificate cert = ks.getCertificate(alias);
            if(cert != null) {
                trustedCerts.add(cert);
            }
```

I believe if we just remove the getCertificate, it'll work just fine, since "getCertificateChain" pulls out the entire chain from the keystore. Alas I'm not in a good position to test that change fully right now.

Oh, you might notice that the "self-signed" root CA in the openssl output is missing. Emitting the root CA is actually unnecessary, since the client _must_ ignore it. Having it in there (and thus inside the keystore) is harmless but adds a bit more network bandwidth. (Actually, the root certificate coupled with the duplicated server certificate caused additional problems, which I alleviated most (not all) by removing the root from the keystore. I suggest that the docs be updated slightly.

Thank you for your consideration!

**Comment by floragunncom** [comment]
Thx, will look into it

**Comment by floragunncom** [comment]
Can you retest with that version: https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-ssl/2.3.5.16-SNAPSHOT/search-guard-ssl-2.3.5.16-20160827.100811-1.zip

**Comment by chmarr** [comment]
Thanks kindly for providing a quick patch. It didn't solve the problem, and I seem to be getting inconsistent results depending on how I'm doing the connection on the client side. There's something the server side is doing that triggers the problem, but I don't know where it is yet. I'm doing further analysis here and I'll let you know. Just FYI, the client side code I'm using works perfectly if I point it to, say, an apache server with SSL installed.

**Comment by floragunncom** [comment]
Can you post the output from ``openssl -s_client`` for the patched version?

For me (with the certificates generated via the example.sh script) it looks now like this:
<pre>
$ openssl s_client -connect localhost:9200  -CAfile example-pki-scripts/ca/root-ca.pem
---
Certificate chain
 0 s:/C=DE/L=Test/O=Test/OU=SSL/CN=node-0.example.com
   i:/DC=com/DC=example/O=Example Com Inc./OU=Example Com Inc. Signing CA/CN=Example Com Inc. Signing CA
 1 s:/DC=com/DC=example/O=Example Com Inc./OU=Example Com Inc. Signing CA/CN=Example Com Inc. Signing CA
   i:/DC=com/DC=example/O=Example Com Inc./OU=Example Com Inc. Root CA/CN=Example Com Inc. Root CA
 2 s:/DC=com/DC=example/O=Example Com Inc./OU=Example Com Inc. Root CA/CN=Example Com Inc. Root CA
   i:/DC=com/DC=example/O=Example Com Inc./OU=Example Com Inc. Root CA/CN=Example Com Inc. Root CA
</pre>

**Comment by floragunncom** [comment]
no feedback. Solution: remove the duplicated certificate but root certificate will be kept (for now)

**Comment by floragunncom** [comment]
python client are working well now, see https://github.com/floragunncom/search-guard-ssl/tree/master/docker
