### ISSUE TITLE
Not compatible with Elastic 2.4.1 

### ISSUE THREAD

**Issue by neuronring** [floragunncom/search-guard-ssl#39]
Thanks for the opensource. Search-guard-ssl is not working with Elasticsearch 2.4.1 do you plan on the release the compatible version.

**Comment by jochenkressin** [comment]
Hi there - ES 2.4.1 is supported for quite a while now. The compatible SG version is 2.4.1.16. 

Here's a list of all SG SSL versions:
https://github.com/floragunncom/search-guard-ssl/wiki

**Comment by neuronring** [comment]
Can you provide me the link ? I tried downloading this version https://github.com/floragunncom/search-guard-ssl/archive/master.zip and it did not work. Says incompatible elastic version.

**Comment by neuronring** [comment]
Thank you very much. I found it from the tag version. You are doing a great contribution to the community.
