### ISSUE TITLE
SG SSL fails in ES Cluster environment

### ISSUE THREAD

**Issue by neuronring** [floragunncom/search-guard-ssl#44]
I configured searchguard in a single node elastic search environment and connection from Kibana also succeeds. All worked fine as expected. 

But when I tried to do the same in a cluster environment and getting errors and failures.. Please find the steps i have followed in the configuration. 

For the sake of understanding and explaning the problem i am using ES node 1 ==>10.1.1.1 and ES node 2 ==>10.2.2.2  as example.

    1. Setup Redundant Elastic environment Version 2.4.1
    
     2. Downloaded and installed SG and SG SSL plugin versions for 2.4.1 on both elastic nodes.
    https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-2/2.4.1.8/search-guard-2-2.4.1.8.zip
    https://search.maven.org/remotecontent?filepath=com/floragunn/search-guard-ssl/2.4.1.16/search-guard-ssl-2.4.1.16.zip
 
    3. Generated the keystores and trust stores on 10.1.1.1. Changed the below (ip address part), in the gen_node_cert.sh file inside the example-pki-scripts folder. 
       -ext san=dns:$NODE_NAME.example.com,dns:localhost,ip:10.1.1.1,oid:1.2.3.4.5.5

Did not change anything else. like -dname , 
it is all the default values.          -dname "CN=$NODE_NAME.example.com, OU=SSL, O=Test, L=Test, C=DE" \

     4. Executed the ./example.sh

     5. Stopped the Elastic Search on 10.1.1.1 and copied the node-0-keystore.jks and truststore.jks  to the elasticsearch config folder. /usr/local/etc/elasticsearch/

    6. Added the below to the elasticsearch.yml config file.
     
`searchguard.ssl.transport.keystore_filepath: node-0-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.enable_openssl_if_available: true
`

`searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-0-keystore.jks
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: changeit
`

     7. Started the ES node on 10.1.1.1. No issues,, All started good.  I was able to connect from the browser using https://10.1.1.1:9200 got  "Search Guard not initialized (SG11)" Error
     8.  Then i ran the SGadmin.sh script. Got the below error and it never finished. 
   
    sudo ./sgadmin.sh  -ts /usr/local/etc/elasticsearch/truststore.jks -tspass changeit -ks /usr/local/etc/elasticsearch/node-0-keystore.jks -kspass changeit -cd ../sgconfig/ -icl
       
    Will connect to localhost:9300 ... done
    Contacting elasticsearch cluster 'elasticsearch' and wait for YELLOW clusterstate ...

Ok. then i wanted to try the same on my node 2 ES. 10.2.2.2. 
        
       9.  Executed the same steps. Step 2 through step 7.  Yes i generated the Keystore and truststore files on ES node 2. by changing the IP address in the gen_node_cert.sh file.

       -ext san=dns:$NODE_NAME.example.com,dns:localhost,ip:10.2.2.2,oid:1.2.3.4.5.5
   
     10. Copied the  copied the node-0-keystore.jks and truststore.jks  to the elasticsearch config folder. /usr/local/etc/elasticsearch/ and added the settings in elasticsearch.yml as mentioned in step 6.

But now, as soon as i start elasticsearch on ES node-2  10.2.2.2 , The Both the nodes starts giving errors,, 

Below Errors on ES node-1 10.1.1.1 

       Caused by: sun.security.validator.ValidatorException: 
     PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors

     [ERROR][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [elastic-  searchguardSSL-102693083-1-180420246.searchguard-SSL.apps-ops.boitop.dev1.dev.cloud.com] SSL Problem Received fatal alert: certificate_unknown javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

      [ERROR][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [elastic-searchguardSSL-102693083-1-180420246.searchguard-SSL.apps-ops.boitop.dev1.dev.cloud.com] SSL Problem General SSLEngine problem javax.net.ssl.SSLHandshakeException: General SSLEngine problem

And Search Guard admin initialize on node 2 also.

**Comment by floragunncom** [comment]
`PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors` indicates a problem with your certificate chain. Have you also changed the certificate signing request part in  `gen_node_cert.sh`? You must do your IP changes in line 37 and 51 in https://github.com/floragunncom/search-guard-ssl/blob/master/example-pki-scripts/gen_node_cert.sh

**Comment by neuronring** [comment]
Yes. I have changed the IP in both the places. But, havent done any changes in Lines 36 and 50.
Also in lines 37 and 51, the dns:localhost is still the same, I did not change it too. just the ip address change

**Comment by floragunncom** [comment]
Why do you add your IP when setting `searchguard.ssl.transport.enforce_hostname_verification: false` (thats ok, but it does not help you in any way)? dns and ip SAN entries are only useful in combination with hostname verification.

Regarding you sgadmin execution which hangs: You must not execute sgadmin with a node certificate (-ks) but with a client certificate (who`s DN is promoted to admin in elasticsearch.yml)

Last: If you execute example.sh twice you will get two different truststore.jks with different root certificates. Just execute example.sh **only once** and use only those certificates and stores created by this run. Thats why the certificates of your nodes didn't work together.

**Comment by neuronring** [comment]
`Why do you add your IP when setting searchguard.ssl.transport.enforce_hostname_verification: false`

I just gave it a try to see if that would help. 

`You must not execute sgadmin with a node certificate (-ks) but with a client certificate (who`s DN is promoted to admin in elasticsearch.yml)`

Not sure what you mean by Client Certificate. I referred an answer provided you here and it says node certificate. 
https://github.com/floragunncom/search-guard/issues/136

`If you execute example.sh twice you will get two different truststore.jks with different root certificates. Just execute example.sh only once and use only those certificates and stores created by this run. `

Makes sense. I understand. But how do i generate two node certificates with different IP addresses at the same time by running ./example.sh

**Comment by neuronring** [comment]
Okay.. I managed to make a copy of example.sh and gen_node_cert.sh and generated two node certificates one per each node with a different IP address with two different gen_node_cert.sh  containing the IP address of respective nodes.  It all works fine,But i keep getting this WARNING, every second on both the nodes.

`[2016-12-06 22:01:21,369][WARN ][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [elastic-searchguardSSL-102693083-1-180420246.searchguard-SSL.apps-ops.boitop.dev1.dev.cloud.com] Someone speaks plaintext instead of ssl, will close the channel
`

**Comment by floragunncom** [comment]
`Someone speaks plaintext instead of ssl, will close the channel` means that you try to connect via HTTP (instead of HTTPS) from somewhere.
