### ISSUE TITLE
Need release for ES 5.2

### ISSUE THREAD

**Issue by brandond** [floragunncom/search-guard-ssl#48]
ES 5.2 was released 2017-01-31
> https://www.elastic.co/blog/elasticsearch-5-2-0-released

**Comment by floragunncom** [comment]
Release is scheduled for monday. 

Do you like to help testing a pre-release?

**Comment by brandond** [comment]
Love to!

**Comment by floragunncom** [comment]
SSL Only: https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-ssl/5.2.0-18-SNAPSHOT/search-guard-ssl-5.2.0-18-20170203.102117-1.zip

SG (including SSL): https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-5/5.2.0-10-SNAPSHOT/search-guard-5-5.2.0-10-20170201.161553-3.zip

(do not install both together)

**Comment by brandond** [comment]
```
[root@ip-10-12-41-115 ~]# /usr/share/elasticsearch/bin/elasticsearch-plugin install -b file:///opt/sgssl/search-guard-ssl-5.2.0-18-20170203.102117-1.zip
-> Downloading file:///opt/sgssl/search-guard-ssl-5.2.0-18-20170203.102117-1.zip
[=================================================] 100%  
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [search-guard-ssl] is incompatible with Elasticsearch [5.2.0]. Was designed for version [5.1.1]
```

**Comment by floragunncom** [comment]
Sorry, try this https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-ssl/5.2.0-18-SNAPSHOT/search-guard-ssl-5.2.0-18-20170204.110436-2.zip

**Comment by floragunncom** [comment]
5.2 compatible version released
