### ISSUE TITLE
Cannot disable SearchGuard SSL

### ISSUE THREAD

**Issue by dylanmei** [floragunncom/search-guard-ssl#49]
With the plugin installed, and `searchguard.ssl.transport.enabled` set to `false`, it is impossible to start ElasticSearch.

```
 org.elasticsearch.bootstrap.StartupException: ElasticsearchException[Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]]

....

Caused by: java.lang.IllegalStateException: searchguard.ssl.transport.enabled must be set to 'true'
```

**Comment by floragunncom** [comment]
With only search-guard-ssl plugin installed you should not face this exception, but with search-guard installed its by design, see https://floragunn.com/search-guard-ssl-tls/

**Comment by dylanmei** [comment]
It makes it difficult to prepare an image that can also be used in a development mode. The promise of a boolean setting is it.... does something. Perhaps remove it entirely?

**Comment by floragunncom** [comment]
Sorry, don't know what you exactly mean. For setting up a development image or a docker container we recommend to use pre-generated certificates which could easily created with https://github.com/floragunncom/search-guard-ssl/blob/master/example-pki-scripts/example.sh . See also https://github.com/deviantony/docker-elk/tree/searchguard

**Comment by floragunncom** [comment]
The settings exists because for search-guard-ssl only you can set it to false, but for search-guard (itself) it mandatory to set it to true. If you have a better solution for this i am glad to accept a PR for that.

**Comment by dylanmei** [comment]
The docker-elk / searchguard branch is very helpful, thanks.
