### ISSUE TITLE
JDK ciphersuite path has no supported ciphers

### ISSUE THREAD

**Issue by slaupster** [floragunncom/search-guard-ssl#5]
Symptom is:

javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)

It looks like the problem is that the cipher spec strings used by openssl are different to the Java CipherSuite strings (insanely!).  

EG:

openssl: **TLS**_RSA_WITH_AES_128_CBC_SHA256
jdk:         **SSL**_RSA_WITH_AES_128_CBC_SHA256

As a result, the intersection of preferred ciphers and JDK supported ciphers is an empty set.

I was going to make a pull request that used netty's io.netty.handler.ssl.CipherSuiteConverter to derive the JDK cipher suite strings until I realised that that is a package private class.  Tomcat has a (possibly better because it takes into account the protocol) public equivalent but that creates a dependency on Apache again.

Seems there is no way to simply use the RFC codes for the ciphers and we are stuck with Strings.

Might be simpler to simply maintain 2 versions of the preferred ciphers list, an openssl one and a JDK one.

Am I missing something ?

**Comment by floragunncom** [comment]
can you check if this https://github.com/floragunncom/search-guard-ssl/commit/79ecaea89f7cc1606392bfb945554e85f2c444e2 fix the issue?

**Comment by slaupster** [comment]
thanks for the prompt response floragunncom!  Unfortunately I won't be able to test this any time soon as I've been pulled off on to other stuff.  The changes do look like they will fix the issue, however.  If I do get a chance I will of course update here.

**Comment by floragunncom** [comment]
@slaupster feel free to reopen if not fixed
