### ISSUE TITLE
Release for 5.2.2

### ISSUE THREAD

**Issue by JoeOrtiz** [floragunncom/search-guard-ssl#53]
Curious if we can get a release for 5.2.2?

**Comment by floragunncom** [comment]
Sure, as soon S3 is working again and day=='Sunday' (we push out new releases normally on Sunday and we need a day or two to prepare the release and run the test suites)

**Comment by JoeOrtiz** [comment]
Sweet...thx.

**Comment by floragunncom** [comment]
Released
