### ISSUE TITLE
Cannot access keystore via symlinks

### ISSUE THREAD

**Issue by tlrdstd** [floragunncom/search-guard-ssl#54]
Per https://github.com/floragunncom/search-guard-ssl/blob/5.2.0/src/main/java/com/floragunn/searchguard/ssl/DefaultSearchGuardKeyStore.java#L530, `LinkOption.NOFOLLOW_LINKS` is explicitly set. This prevents me from storing my keystore/truststore in a central location and symlinking them from the Elasticsearch directory.

Please remove this `NOFOLLOW_LINKS` flag to allow for a more flexible configuration.

**Comment by floragunncom** [comment]
not sure if it is a good idea to let Search Guard follow symlinks for ssl related files. We explicitly set NOFOLLOW_LINKS for security reasons to protect sysadmins from symlink related threats.

**Comment by tlrdstd** [comment]
Generally speaking, if a sysadmin is concerned that someone has malicious read/write perms on his box to redirect or edit a symlink, then it's completely game over anyway. With that level of access, I'm not sure how app-level security is going to matter. The malicious actor could just update the non-symlinked version anyway.

For my team, this no-symlink restriction leads to a more complicated configuration, with multiple copies of our keystore copied around the server. For us, a decentralized, harder-to-manage set of keystores leads to weaker security.

**Comment by floragunncom** [comment]
Why you need multiple copies of your keystore?

**Comment by tlrdstd** [comment]
We have a central keystore that we use for any Java code. It lives in a known, central location.

I want to symlink the `search-guard-ssl` keystore to point to that known, central location. `NOFOLLOW_LINKS` prevents me from doing so. The only other way for `search-guard-ssl` to access my central keystore is for me to copy that keystore into the `config` directory.

This instantly produces a fragmented approach to keystore management.

**Comment by floragunncom** [comment]
After a few tests it appears that the elasticsearch security manager configuration allows only files to be read if they reside in the config/ dir. So following symlinks here would just end up in another error message.
