### ISSUE TITLE
Searchguard for nxlog server

### ISSUE THREAD

**Issue by yasvanth** [floragunncom/search-guard-ssl#55]
Hi All,
To make it clear, I am using nxlog instead of logstash to load data to elasticsearch. After installing SG nxlog fails to connect to elasticsearch ( nxlog server runs on same server).  The error what is receiving is 
`2017-03-21 13:10:36 ERROR SSL error, SSL_ERROR_SSL: retval 0, sslv3 alert certificate unknown,` 

My nxlog server config is 
`
   Module om_ssl
   Host localhost
   Port 9200
   CertFile /etc/ssl/elastic/CN=sgadmin.all.pem
   CertKeyFile /etc/ssl/elastic/CN=sgadmin.key.pem
   CAFile /etc/ssl/elastic/root-ca.pem
   ContentType application/json
   Exec    if $raw_event !~ /EventReceivedTime/ { log_error("Droping "+$raw_event); drop(); }
   Exec    set_http_request_path(strftime(now(), "/ucd_test-%Y.%m.%d/" + $SourceModuleName)); rename_field("timestamp","@timestamp");
   `

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
