### ISSUE TITLE
Make elasticsearch.yml free from secrets: keystore passwords

### ISSUE THREAD

**Issue by bw498c** [floragunncom/search-guard-ssl#56]
I would like to see where the elasticsearch.yml is free from sensitive information. This would be beneficial when sharing the elasticsearch.yml for support. Currently, I have to supply passwords for my keystores and truststore in the elasticsearch.yml.

It would be great if I could reference passwords in a separate file, as I want to supply configuration with a kubernetes secret with just a volume mount.

**Comment by floragunncom** [comment]
Thats a good idea but it seems elasticsearch itself prepares something for it: https://github.com/elastic/elasticsearch/pull/22335

**Comment by bw498c** [comment]
If I am reading this right, you would have to use the SecureSetting class for some of SG-SSL settings, right?

**Comment by floragunncom** [comment]
The whole thing seems to not be finally complete (https://github.com/elastic/elasticsearch/issues/22475) so we wait at least for 5.4 to take a deeper look into this. If you like to help us here do not hesitate to file a PR.

**Comment by floragunncom** [comment]
Lets reopen this to track progress

**Comment by floragunncom** [comment]
relates https://github.com/floragunncom/search-guard/issues/325

**Comment by jochenkressin** [comment]
Seems like SecureSettings are usable from ES 5.4.0 onwards. 

We've started working on it, internal issue number is SG-357.

**Comment by floragunncom** [comment]
I suggest to create an sg internal abstraction so that we also can use other secure storages like Vault

**Comment by floragunncom** [comment]
Currently we recommend to use environment variables to keep elasticsearch.yml and the Search Guard yaml fiiles free from plain text passwords.

No further work planned so far in the near future for anything else.
