### ISSUE TITLE
No such keystore file

### ISSUE THREAD

**Issue by vroomvroomvroom** [floragunncom/search-guard-ssl#6]
Seeing the same thing as Issue #1 (closed) on Linux .. 

service elasticsearch start                                                                               
Starting elasticsearch: Exception in thread "main" ElasticsearchException[No such keystore file /etc/elasticsearch]
        at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:154)
        at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:112)
        at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
        at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:84)
        at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:224)
        at org.elasticsearch.node.Node.<init>(Node.java:168)
        at org.elasticsearch.node.Node.<init>(Node.java:129)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.
                                                           [FAILED]

uncommented lines from elasticsearch.yml:
grep -v "#" /etc/elasticsearch/elasticsearch.yml|sort|uniq

bootstrap.mlockall: true
cluster.name: deves1
discovery.zen.ping.multicast.enabled: false
logger.com.floragunn.searchguard.ssl: DEBUG 
node.name: "DEV Saul Kripke"
path.data: /opt/share/elasticsearch/2.1/
path.plugins: /usr/share/elasticsearch/plugins/
searchguard.allow_all_from_loopback: true
searchguard.auditlog.enabled: true
searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend
searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator
searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.clientcert.HTTPSClientCertAuthenticator
searchguard.enabled: true
searchguard.key_path: /var/lib/elasticsearch/searchguard_node_key.key
searchguard.ssl.transport.http.keystore_filepath: /etc/elasticsearch/identity.jks
searchguard.ssl.transport.http.keystore_password: nopasswd4u
searchguard.ssl.transport.http.keystore_type: JKS
searchguard.ssl.transport.http.truststore_filepath: /etc/elasticsearch/trust.jks
searchguard.ssl.transport.http.truststore_password: nopasswd4u
searchguard.ssl.transport.http.truststore_type: JKS
searchguard.ssl.transport.node.enabled: true
searchguard.ssl.transport.node.encforce_hostname_verification.resolve_host_name: true
searchguard.ssl.transport.node.enforce_clientauth: true
searchguard.ssl.transport.node.keystore_filepath: /etc/elasticsearch/identity.jks
searchguard.ssl.transport.node.keystore_password: nopasswd4u
searchguard.ssl.transport.node.keystore_type: JKS
searchguard.ssl.transport.node.truststore_filepath: /etc/elasticsearch/trust.jks
searchguard.ssl.transport.node.truststore_password: nopasswd4u
searchguard.ssl.transport.node.truststore_type: JKS
security.manager.enabled: false

**Comment by vroomvroomvroom** [comment]
found another detail just prior in logs:
[2016-02-05 11:25:10,207][INFO ][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Open SSL not available because of java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL
[2016-02-05 11:25:10,254][ERROR][bootstrap                ] Exception
ElasticsearchException[No such keystore file /etc/elasticsearch]

this may be related to netty version:

https://github.com/netty/netty/issues/3293

from your .pom:
using netty:
4.0.34.Final
and ssl: 
<version>1.1.33.Fork11</version>

yet above issue notes fixed in fork
 1.1.32.Fork1
and main netty version is now 4.1.
merge tree for those shows .. cannot be displayed, too many forks. :(

**Comment by vroomvroomvroom** [comment]
also confirmed it is isolated to when plugin installed:
 
$ bin/plugin remove search-guard-ssl                                                                                    
-> Removing search-guard-ssl...
Removed search-guard-ssl

$ service elasticsearch start                                                                                           
Starting elasticsearch: 
                                                           [  OK  ]

**Comment by floragunncom** [comment]
all keystore and truststore locations are relative to the config directory, you may not use absolute path here.

<pre>
# **Relative** path to the truststore file (mandatory, this stores the client/root certificates), must be placed under the config/ dir
#searchguard.ssl.transport.truststore_filepath: truststore.jks
</pre>

**Comment by floragunncom** [comment]
don't see why and how https://github.com/netty/netty/issues/3293 is related to "java.lang.ClassNotFoundException: org.apache.tomcat.jni.SSL". If you want to use Open SSL be sure to follow these steps https://github.com/floragunncom/search-guard-ssl/wiki/Open-SSL-setup

**Comment by vroomvroomvroom** [comment]
now THAT makes sense .. i'll give it a go Monday, thanks!

**Comment by floragunncom** [comment]
feel free to reopen if this is still an issue

**Comment by vroomvroomvroom** [comment]
All good needed relative path thanks

Erik Swanson

**Comment by Desjeunf** [comment]
Hello everyone. 

Have exactly the same issue and still not resolved...

Here is my plugins/search-guard-2/sgconfig/elasticsearch.yml

```
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: node-1-keystore.jks
searchguard.ssl.transport.keystore_alias: node-1
searchguard.ssl.transport.keystore_password: azerty

searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_alias: root-ca
searchguard.ssl.transport.truststore_password: azerty
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.transport.enable_openssl_if_available: true
```

and the error log : 
```
[2016-03-02 10:19:25,767][ERROR][bootstrap                ] Exception
ElasticsearchException[No such keystore file /etc/elasticsearch]
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:162)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:130)
	at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:113)
	at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:263)
	at org.elasticsearch.node.Node.<init>(Node.java:166)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Have you any idea of what I'm doing wrong ?

Thank you very much for your help.

**Comment by vroomvroomvroom** [comment]
use relative paths, that fixed for me

**Comment by m0numentum** [comment]
Doesn't it what I already do ?

**Comment by floragunncom** [comment]
yes, but /etc/elasticsearch/node-1-keystore.jks and /etc/elasticsearch/truststore.jks seems not existent.

**Comment by m0numentum** [comment]
Thought I copied the files in both /usr/share/elasticsearch/plugins/search-guard/sgconfig and /etc/elasticsearch. 
I verified also that Elasticsearch can read these files by giving 0777 permission

**Comment by floragunncom** [comment]
How do you installed Elasticsearch? By .rpm/.deb or puppet os similar? Where is your elasticsearch.yml file? Normally the keystores have to be in the same directory as the elasticsearch.yml (the config directory)

**Comment by m0numentum** [comment]
I installed Elasticsearch via repositories and my elasticsearch.yml is in /etc/elasticsearch. But I have /usr/share/elasticsearch/search-guard/sgconfig/elasticsearch.yml file too and I have a doubt on the file I have to edit to make it work

**Comment by floragunncom** [comment]
/usr/share/elasticsearch/search-guard/sgconfig/elasticsearch.yml is not relevant, only /etc/elasticsearch/elasticsearch.yml is

**Comment by m0numentum** [comment]
Ok but if I edit /etc/elasticsearch/elasticsearch.yml, Elasticsearch doesn't restart (I'm facing a beautiful 'FAILED'), while I'm editing /usr/share/elasticsearch/search-guard/sgconfig/elasticsearch.yml, Elasticsearch gives me a 'OK' when restarting

**Comment by floragunncom** [comment]
Check the logs what is the reason for getting a FAILED

**Comment by m0numentum** [comment]
Thank you for taking time to help. 

So here is the message when I restart Elasticsearch:
```
root@vmtest:/etc/elasticsearch# /etc/init.d/elasticsearch restart
[ ok ] Stopping Elasticsearch Server: Elasticsearch Server is not running but pid file exists, cleaning up.
[FAIL] Starting Elasticsearch Server: failed!
```

and here is the log file:
```
[2016-03-03 10:13:34,910][ERROR][bootstrap                ] Exception
ElasticsearchException[No such keystore file /etc/elasticsearch]
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:162)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:130)
	at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:113)
	at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:263)
	at org.elasticsearch.node.Node.<init>(Node.java:166)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

Here is the content of the Elasticsearch directory (/etc/elasticsearch):
```
root@vmtest:/etc/elasticsearch# ls -l 
total 24
-rwxr-x--- 1 root          elasticsearch 3789 mars   3 10:14 elasticsearch.yml
-rwxr-x--- 1 root          elasticsearch 2571 janv. 27 14:39 logging.yml
-rw-r--r-- 1 elasticsearch elasticsearch 4134 mars   3 10:14 node-1-keystore.jks
drwxr-x--- 2 root          elasticsearch 4096 janv. 27 14:39 scripts
-rw-r--r-- 1 elasticsearch elasticsearch 1916 mars   3 10:14 truststore.jks
```
and the elasticsearch.yml file:

```
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
 cluster.name: test
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
 node.name: node-1
#
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
 path.data: /home/franck/elasticsearch
#
# Path to log files:
#
# path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
# bootstrap.mlockall: true
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
# http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
# discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
# discovery.zen.minimum_master_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
# gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true
searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: node-1-keystore.jks
searchguard.ssl.transport.keystore_alias: node-1
searchguard.ssl.transport.keystore_password: azerty

searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_alias: root-ca
searchguard.ssl.transport.truststore_password: azerty
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.transport.enable_openssl_if_available: true
```

Am I doing it wrong ? 

Thanks again for your patience

**Comment by floragunncom** [comment]
can you pls add the following line to elasticsearch.yml and see if you can start elasticsearch?

<pre>
searchguard.ssl.transport.enabled: false
</pre>

**Comment by m0numentum** [comment]
It doesn't resolve anything same error unfortunately

**Comment by floragunncom** [comment]
then you're editing the wrong elasticsearch.yml file.

Pls. post result of
<pre>
sudo find / -iname elasticsearch.yml
</pre>

**Comment by m0numentum** [comment]
Here is what I have:

```
root@vmtest:/etc/elasticsearch# find / -iname elasticsearch.yml
/etc/elasticsearch/elasticsearch.yml
/usr/share/elasticsearch/plugins/search-guard-2/sgconfig/elasticsearch.yml
```

**Comment by floragunncom** [comment]
pls delete (just to prevent editing the wrong file):
<pre>
rm /usr/share/elasticsearch/plugins/search-guard-2/sgconfig/elasticsearch.yml
</pre>

Then adding
<pre>
searchguard.ssl.transport.enabled: false
</pre>
to /etc/elasticsearch/elasticsearch.yml must definitively prevent your error, because with this option the code which causes you problem will never be executed. Maybe you have a problem in your /etc/elasticsearch/elasticsearch.yml with non visible characters or tabs or encoding or something like that. Display invisible characters with vi: http://askubuntu.com/questions/74485/how-to-display-hidden-characters-in-vim

**Comment by floragunncom** [comment]
Another guess. Give the keystore execute perms:

<pre>
sudo chmod +x /etc/elasticsearch/*.jks
</pre>

**Comment by m0numentum** [comment]
I think I'm not very lucky... Always the same error

**Comment by vroomvroomvroom** [comment]
try using keystore and truststore names without dashes in them.  i think i
had to use underscores and that did work. just forget which app (elastic,
kibana, logstash or nginx) i had to do that for ..

**Comment by m0numentum** [comment]
It doesn't resolve my problem too... But I'm wondering if dashes are a problem in aliases field too ?

**Comment by floragunncom** [comment]
no clue so far, sorry. Maybe try installing elasticsearch via tar.gz and get SG running. After that is working successfully purge and reinstall the package and setup SG according to the working tar.gz installation.
I will prepare a vagrant box to show thats and how its working.

**Comment by crazy24** [comment]
Ran the below command to install search guard:

 ./tools/sgadmin.sh --configdir sgconfig/ --keystore /elasticsearch-2.3.2/kirk-keystore.jks --keystore-password changeit --truststore /elasticsearch-2.3.2/truststore.jks --truststore-password changeit –disable-host-name-verification

Below is the response received:

Connect to localhost:9300
Exception in thread "main" ElasticsearchException[Unable to read /elasticsearch-2.3.2/kirk-keystore.jks (/elasticsearch-2.3.2/kirk-keystore.jks) Please make sure this files exists and is readable regarding to permissions]
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.checkStorePath(SearchGuardKeyStore.java:447)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.initSSLConfig(SearchGuardKeyStore.java:177)
	at com.floragunn.searchguard.ssl.SearchGuardKeyStore.<init>(SearchGuardKeyStore.java:136)
	at com.floragunn.searchguard.ssl.SearchGuardSSLModule.<init>(SearchGuardSSLModule.java:29)
	at com.floragunn.searchguard.ssl.SearchGuardSSLPlugin.nodeModules(SearchGuardSSLPlugin.java:116)
	at org.elasticsearch.plugins.PluginsService.nodeModules(PluginsService.java:263)
	at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:139)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:134)


ELASTIC SERACH configured correctly. and running.

Below(Along with searchguard configuration) is the elasticsearch.yml file located in /installation_dir/elasticsearch-2.3.2/config 


### # ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#	Before you set out to tweak and tune the configuration, make sure you
#	understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
# cluster.name: my-application
cluster.name: MTML
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
# node.name: node-1
node.name: ironman
#
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
# path.data: /path/to/data
#
# Path to log files:
#
# path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
# bootstrap.mlockall: true
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
# network.host: 192.168.0.1
network.host: 0.0.0.0
#
# Set a custom port for HTTP:
#
# http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
# discovery.zen.ping.unicast.hosts: ["host1", "host2"]
discovery.zen.ping.unicast.hosts: ["41.223.76.73"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
# discovery.zen.minimum_master_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
# gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#                                                                                            
# action.destructive_requires_name: true
index.number_of_shards: 2
index.number_of_replicas: 0
#bootstrap.mlockall: true
#indices.store.throttle.max_bytes_per_sec : 100mb
#index.store.type: niofs
#threadpool:
 #   index:
  #	 type: cached
   #     size: 550
    #    queue_size: 15000
     #   processors: 4

#threadpool:
 #   search:
  #     queue_size: 15000

security.manager.enabled: false
searchguard.authcz.admin_dn:
#  - CN=vi, OU=vi, O=vi, L=vi, ST=vi, C=vi
  - CN=kirk, OU=client, O=client, L=Test, C=DE
 # - cn=smith,ou=IT,ou=IT,dc=company,dc=com

**Comment by crazy24** [comment]
Also i have copied 
> kirk-keystore.jks 
>  spock-keystore.jks
> truststore.jks 
 from the '/installation_dir/elasticsearch-2.3.2/plugins/search-guard-ssl/example-pki-scripts' to '/installation_dir/elasticsearch-2.3.2/'

**Comment by ikarmax** [comment]
> It doesn't resolve my problem too... But I'm wondering if dashes are a problem in aliases field too ?

try to check directory permission 
namei -l /etc/elasticsearch/truststore.jks
set o+rx to directory
