### ISSUE TITLE
Signing CA certificate missing from truststore.jks

### ISSUE THREAD

**Issue by dkanbier** [floragunncom/search-guard-ssl#68]
The Search Guard documentation states that when using the example-pki-scripts the generated truststore.jks will contain the root CA and intermediate/signing CA.

However, when running gen_root_ca.sh the resulting truststore.jks file will only contain the root CA. This causes issues when using the keystores with SG, as the SSL chain will be incomplete.

In my environment I've changed this bit of code in gen_root_ca.sh:

```
cat ca/root-ca.pem | "$BIN_PATH" \
    -import \
    -v \
    -keystore truststore.jks   \
    -storepass $TS_PASS  \
    -noprompt -alias root-ca-chain

```
To:
```
cat ca/chain-ca.pem | "$BIN_PATH" \
    -import \
    -v \
    -keystore truststore.jks   \
    -storepass $TS_PASS  \
    -noprompt -alias root-ca-chain
```

I'm not sure if this is an appropiate approach, but now both the root CA and intermediate/signing CA are in the truststore.jks, as the documentation suggests.

**Comment by floragunncom** [comment]
docs corrected: https://github.com/floragunncom/search-guard-docs/commit/479a023a7ca8794f62e2bbedef42ff117e1f0cc2

**Comment by dkanbier** [comment]
Any idea on where to put the signing CA certificate? 

Because now when you follow the demo steps you won't end up with a working environment right? Or do I simply miss something?

**Comment by jochenkressin** [comment]
The scripts in example-pki-scripts are actually ok and will produce working certificates. The doc was incorrect in stating that the intermediate certificate needs to go into the truststore. This is not true: The truststore only contains the Root CA. The intermediate/signing cert goes into the node's keystore. We've updated the docs.

**Comment by dkanbier** [comment]
Yes you are right, I'm not too sure what happened in my setup why I needed to add the intermediate/signing cert to the truststore. I tried, but couldn't reproduce the issue.
