### ISSUE TITLE
Elasticsearch speaks http plaintext instead of ssl, will close the channel

### ISSUE THREAD

**Issue by Passpes** [floragunncom/search-guard-ssl#70]
Hi folks,
I configured ELK with searchguard using v5.5.0.
The solution was working petty good and then when I just restarted the cluster I got some problem in the communication between Logstash and Elasticseacrh - so to limit the problem I stopped logstash to fix ES issue and here's a the logs from Elasticseacrh:
`[2017-08-07T13:26:38,920][WARN ][c.f.s.h.SearchGuardHttpServerTransport] [service01] Someone (/x.x.x.x:41570) speaks http plaintext instead of ssl, will close the channel`
I followed this process by using:
lsof -nP | grep -ie :9200
`java      10795 11508 elasticsearch  794u     IPv4            3127616        0t0        TCP x.x.x.:9200->x.x.x.x:41570 (ESTABLISHED)`
and then catching the process sending data to Elasticsearch:
ps -aux | grep 10795
`elastic+ 10795 11.7 10.6 240378736 3495952 ?   SLsl 12:52   3:37 /bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet -Edefault.path.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefault.path.conf=/etc/elasticsearch`

so from this output I understand that the process 10795 which is a JAVA appalication is sending http plaintext instead of ssl.

How can I fix this problem?

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
