### ISSUE TITLE
search-guard-ssl 0's out tx_size_in_bytes

### ISSUE THREAD

**Issue by jfelege-nm** [floragunncom/search-guard-ssl#75]
We are observing the value of transport.tx_size_in_bytes attribute under the /_nodes/stats API endpoint is always 0 for all nodes when search-guard-ssl is installed. We have been able to reproduce the behavior on both ElasticSearch v5.5.3, v5.6.2 with SSL versions: 5.5.3-23, 5.6.2-23 respectively, on a simplified 3 node cluster (1 acting as master-node, 1 acting as data-node, 1 acting as client-node).

The JVM we are using:
version: "1.8.0_152",
vm_name: "Java HotSpot(TM) 64-Bit Server VM",
vm_version: "25.152-b16",

Steps to reproduce - after installing elasticsearch but before installing search guard, you'll notice transport.tx_size_in_bytes under the /_nodes/stats API will be non-zero (since the individual nodes are communicating with each other). Once search-guard-ssl is installed, the value is always zero.

Just wondering if there are any thoughts as to what might be causing this behavior or is it a known limitation? Or how we might be able to collect the volume of data being sent out over the transport layer given the tx_count attribute is populated with non-zero value.

Thanks for any help you can provide!

**Comment by floragunncom** [comment]
good catch, will have a look. Do you use openssl/tcnative or plain Java SSL?

Do you see also other metrics affected or is really only 'tx_size_in_bytes' which seems to be affcted?

**Comment by jfelege-nm** [comment]
Here's output of the /_searchguard/sslinfo endpoint:

> {
> principal: null,
> peer_certificates: "0",
> ssl_protocol: null,
> ssl_cipher: null,
> ssl_openssl_available: false,
> ssl_openssl_version: -1,
> ssl_openssl_version_string: null,
> ssl_openssl_non_available_cause: "java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL",
> ssl_openssl_supports_key_manager_factory: false,
> ssl_openssl_supports_hostname_validation: false,
> ssl_provider_http: null,
> ssl_provider_transport_server: "JDK",
> ssl_provider_transport_client: "JDK"
> }

> [2017-11-02T17:39:25,619][INFO ][c.f.s.s.DefaultSearchGuardKeyStore] Open SSL not available (this is not an error, we simply fallback to built-in JDK SSL) because of java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL

We have the JCE addons installed.

As for other metrics, no. I've only noticed tx_size_in_bytes affected thus far. There again I just began building out monitoring dashboards for Elastic and happened to stumble upon this first.

Thanks again!

**Comment by floragunncom** [comment]
Can you post (or mail in case it contains confidential informations) the complete output of `/_nodes/stats` as well as `/_nodes`?

**Comment by jfelege-nm** [comment]
@floragunncom - sent via email

**Comment by floragunncom** [comment]
seems like a ES bug: https://github.com/elastic/elasticsearch/issues/27258

**Comment by jfelege-nm** [comment]
thanks for investigating!

**Comment by floragunncom** [comment]
will be fixed upstream with 5.6.9, see https://github.com/elastic/elasticsearch/pull/29194
