### ISSUE TITLE
searchguard  SSL//TLS Received fatal alert: bad_certificate on reindex

### ISSUE THREAD

**Issue by fperalta-stratio** [floragunncom/search-guard-ssl#76]
Hi.
We have configured searchguard TLS/SSL module with the next configuration:
Elasticsearch 5.5.2
searchguard.ssl.http.enabled: true
searchguard.ssl.http.clientauth_mode: REQUIRE
searchguard.ssl.transport.resolve_hostname: false

When we try to launch reindex api from Elasticsearch to create a copy of indexes including the host we get the next Error: 
        "type": "s_s_l_exception",
        "reason": "Received fatal alert: bad_certificate"
    

The sentence is:
curl -k -XPOST --cacert truestore.pem  --cert cert.pem https://coordinator-01:31504/_reindex  -d'{
  "source": {
    "remote": {
      "host": "https://coordinator-01:31504"
    },
    "index": "test"
  },
  "dest": {
    "index": "text2"
  }
}'

**Comment by floragunncom** [comment]
This is already known: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/search-guard/OgvmsMR6mZo/u_QZX_2gBAAJ

Upstream issue is https://github.com/elastic/elasticsearch/issues/27267

**Comment by floragunncom** [comment]
Seem coming with 6.7+ https://github.com/elastic/elasticsearch/pull/37527
