### ISSUE TITLE
Plugin packaging changed (6.0)

### ISSUE THREAD

**Issue by pieterlange** [floragunncom/search-guard-ssl#77]
Elasticsearch: 6.0.0
JVM: OpenJDK 8u131
Number of nodes: not relevant
Description: zip file packaging not conforming to new plugin format

When trying to install the plugin using `./bin/elasticsearch-plugin install https://github.com/floragunncom/search-guard-ssl/archive/ves-6.0.0-24.beta1.zip`:
```-> Downloading https://github.com/floragunncom/search-guard-ssl/archive/ves-6.0.0-24.beta1.zip
[=================================================] 100%   
ERROR: `elasticsearch` directory is missing in the plugin zip
```

This is corroborated by the documentation: https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html

**Comment by floragunncom** [comment]
The correct way to install the plugin is either

`./bin/elasticsearch-plugin install -b https://oss.sonatype.org/content/repositories/releases/com/floragunn/search-guard-6/6.0.0-17.beta1/search-guard-6-6.0.0-17.beta1.zip` (from maven) or

`./bin/elasticsearch-plugin install -b com.floragunn:search-guard-6:6.0.0-17.beta1`

On github we do not provide any binaries.

**Comment by pieterlange** [comment]
I feel stupid now.

Thanks
