### ISSUE TITLE
troubles with the certificates

### ISSUE THREAD

**Issue by carioka88** [floragunncom/search-guard-ssl#8]
Hello,
I am having some troubles to setup and do all the configuration with search-guard-ssl.
I am running Elasticsearch 2.2 and I have 2 data nodes, 1 master node and 1 search node.

I have my truststore.jks and keystore.jks in every node, created according to the wiki. 
When running ES, I got these many errors.. as:
`[DEBUG][com.floragunn.searchguard.ssl.SearchGuardKeyStore] Open SSL ALPN supported false`
or
```

[DEBUG][io.netty.handler.ssl.OpenSslEngine] SSL_read failed: OpenSSL error: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
[WARN ][com.floragunn.searchguard.ssl.transport.SearchGuardSSLNettyTransport] [training-4-es] exception caught on transport layer [[id: 0xdc94ff7c, /188.184.184.65:58737 => training-es.example.ch/128.142.244.51:9300]], closing connection
javax.net.ssl.SSLHandshakeException: error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown
```

If it is a problem with the certificates...is there any way of debugging that I can see the certificate that it is unknown?
Any idea about what kind of error could I have done?
Also I do not understand well the certificate for the server or client...when you have different data, master and search nodes, which one would act as a service? the master? the search one?
I am still very new in the certificates topic, ES and search-guard plugin!

Any kind of help is very welcome!
Thanks in advance,

Rocio

**Comment by floragunncom** [comment]
"Open SSL ALPN supported false" is not an error, its logged on a DEBUG level (all which is logged on DEBUG or INFO you can safely ignore, that are not errors). Do you have disabled hostname verification in elasticsearch.yml? If not pls. do that an try again. If thats not working either then pls. generate certificates by running example.sh in example-pki-scripts/ and check if these certificates are working. And have a look into https://github.com/floragunncom/search-guard-ssl/blob/master/demo/setup_sg.sh to see how a working config looks like.

**Comment by carioka88** [comment]
Thanks!
I was not adding correctly the chain!
The ticket can be close :)
