### ISSUE TITLE
Confuse about pki script

### ISSUE THREAD

**Issue by tieungao88** [floragunncom/search-guard-ssl#80]
Hi team,
I saw two file create node_cert: gen_node_cert.sh and gen_node_cert_openssl.sh. Can you tell me about different of them?, and when I deploy, what will I use?

Thanks.

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
