### ISSUE TITLE
Search Guard should not strip the root CA

### ISSUE THREAD

**Issue by GrahamDennis** [floragunncom/search-guard-ssl#81]
This line is wrong. You should send the full certificate chain.
https://github.com/floragunncom/search-guard-ssl/blob/a574f5a9a961b015e65c04f797b220a4cd1a8c7f/src/main/java/com/floragunn/searchguard/ssl/util/SSLCertificateHelper.java#L41

**Comment by floragunncom** [comment]
According to [RFC5246 Section 7.4.2](https://tools.ietf.org/html/rfc5246#section-7.4.2) its allowed to omit the root certificate authority as well as sending it.

<pre>
certificate_list
      This is a sequence (chain) of certificates.  The sender's
      certificate MUST come first in the list.  Each following
      certificate MUST directly certify the one preceding it.  Because
      certificate validation requires that root keys be distributed
      independently, the self-signed certificate that specifies the root
      certificate authority MAY be omitted from the chain, under the
      assumption that the remote end must already possess it in order to
      validate it in any case.
</pre>

**Comment by floragunncom** [comment]
@GrahamDennis ping

**Comment by GrahamDennis** [comment]
Yes, you’re right. I was trying to figure out why something wasn’t working and I thought the problem was the missing root cert but you’re correct, that shouldn’t have been the problem. 

Many things do send the root CA, but it should be fine not to too. Please close
