### ISSUE TITLE
LibreSSL support?

### ISSUE THREAD

**Issue by denji** [floragunncom/search-guard-ssl#82]
* https://www.libressl.org
* https://opensslrampage.org
* https://ftp.openbsd.org/pub/OpenBSD/LibreSSL
* https://github.com/libressl-portable/

https://github.com/floragunncom/search-guard-docs/commit/08c7369120e60b13a30deb6d5554cd9c61422017 OpenSSL for maximum performance, but not security.

**Comment by floragunncom** [comment]
Yes, there is also support for libressl and boringssl like described here http://docs.search-guard.com/latest/openssl#enabling-openssl

We also provide binaries for libressl bindings here https://dl.bintray.com/floragunncom/netty-tcnative/

If that does not fit for you you get the maximum security of course compiling all the stuff yourself for your platform. Search Guard SSL + Netty are open source so also this should not be a problem.
