### ISSUE TITLE
Test failure: OpenSSLTest.testEnsureOpenSSLAvailability:48 OpenSSL not available: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_osx_x86_64, netty_tcnative]

### ISSUE THREAD

**Issue by minfrin** [floragunncom/search-guard-ssl#83]
The release ves-6.2.2-25.1 being built on MacOS Sierra / Java9 without OpenSSL available fails as follows:

[ERROR] Failures: 
[ERROR]   OpenSSLTest.testEnsureOpenSSLAvailability:48 OpenSSL not available: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_osx_x86_64, netty_tcnative]
[INFO] 
[ERROR] Tests run: 46, Failures: 1, Errors: 0, Skipped: 15
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:45 min
[INFO] Finished at: 2018-02-27T18:37:07+02:00
[INFO] Final Memory: 39M/128M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.20.1:test (default-test) on project search-guard-ssl: There are test failures.
[ERROR] 

This did not fail when I built v6.0.0.

**Comment by floragunncom** [comment]
`export SG_TEST_OPENSSL_OPT=true` should fix this. 

Please be aware that Java 9 ist not yet officially supported.
