### ISSUE TITLE
The SearchGuardSSlPlugin does not allow empty trust store passwords

### ISSUE THREAD

**Issue by cosmin79** [floragunncom/search-guard-ssl#90]
Having seen https://github.com/floragunncom/search-guard-ssl/issues/16 , I still encounter this issue while trying to get the ES 6.X transport client to work with the SearchGuardSSlPlugin. The versions I'm using are:
1) ES transport client 6.2.1
2) SearchGuardSsl 6.2.1-25.1
3) a `truststore.jks` with only public certs, thus not requiring a password.

In https://github.com/floragunncom/search-guard-ssl/blob/master/src/main/java/com/floragunn/searchguard/ssl/DefaultSearchGuardKeyStore.java#L232 , a default password is used if none is provided in the ES client settings. I've tried to provide both "" (empty string) and null as value for the `SEARCHGUARD_SSL_HTTP_TRUSTSTORE_PASSWORD` parameter. However, the problem is that the ES 6.X pre built transport client filters out all the setting entries with empty values. That means that by the time the `SearchGuardSSLPlugin` gets the settings to initialize itself with, it will not have a truststore password setting (and thus assume "changeit" is the one).

**Comment by floragunncom** [comment]
For this we recommend to use pem certificates instead of JKS/PKCS12
