### ISSUE TITLE
example.sh not found

### ISSUE THREAD

**Issue by yabir** [floragunncom/search-guard-ssl#91]
I'm following these instructions but there isn't any file called example.sh

https://docs.search-guard.com/latest/tls-certificates-sample-scripts

If is not there, could you update the documentation?

**Comment by jochenkressin** [comment]
It's there, you need to download the Search Guard SSL repository as mentioned in the docs:

"First download the Search Guard SSL source code onto your machine. You can either clone the repository, or download it as zip file."

Latest version is:

[https://github.com/floragunncom/search-guard-ssl/tree/es-6.3.0](https://github.com/floragunncom/search-guard-ssl/tree/es-6.3.0)

And the mentioned script is in the example-pki-folder:

[https://github.com/floragunncom/search-guard-ssl/tree/es-6.3.0/example-pki-scripts](https://github.com/floragunncom/search-guard-ssl/tree/es-6.3.0/example-pki-scripts)
