### ISSUE TITLE
Cannot send logs to ES with HTTPS URL

### ISSUE THREAD

**Issue by JaisonRPA** [floragunncom/search-guard-ssl#92]
I have installed "SearchGaurd" plugin (community edition)on ElasticSearch 6.3.2(OS- Windows server 2012 R2), everything works fine from ES & Kibana & searchGaurd perspective which is expected. 

The issue backgroud:

I have configured RPA tool to send a log files to ES which worked fine until I install SG ( with http://<host>:9200 url, it was working fine).

After SG installtion , RPA tool could not send the logs to ES because of https ES URL  - I found and captured the Event viewer log as below

"A fatal alert was received from the remote endpoint. The TLS protocol defined fatal alert code is 40" 
A fatal error occurred while creating an SSL client credential. The internal error state is 10013."

I've used TLS certificates(root-ca,noded,client) generated by TLS tools from SG. I suspect the root CA which created is not authorized inside our organization. 

Any solution/ideas/fix would be much appreciated.

Thanks,
Jaison R

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
