### ISSUE TITLE
Can't do bulk insertions by using Java code

### ISSUE THREAD

**Issue by VinothKumarKannan** [floragunncom/search-guard-ssl#93]
SearchGuard Version=6 
elastic search version =6.3.2
Java Versoin =1.8

When I try  to insert a data by using transport clien am getting error like **below**

**[ERROR][c.f.s.f.SearchGuardFilter] No user found for indices:data/write/bulk from 127.0.0.1:53479 TRANSPORT via netty {_sg_initial_action_class_header=BulkRequest}**

My Settings configurations:
**Settings.Builder settingsBuilder =  Settings.builder()
 .put("searchguard.ssl.transport.pemcert_filepath", CommonConstants.SSL_KEY_LOCATION +"esnode.pem")
 .put("searchguard.ssl.transport.pemkey_filepath", CommonConstants.SSL_KEY_LOCATION + "esnode-key.pem")
 .put("searchguard.ssl.transport.pemtrustedcas_filepath", CommonConstants.SSL_KEY_LOCATION + "root-ca.pem")
 .put("searchguard.ssl.transport.enabled", "true")								  .put("searchguard.ssl.transport.enforce_hostname_verification", "false")									  .put("path.home", "/");**

  **Settings settings = settingsBuilder.build();**

TransPort Client Config
  **transportClient = new PreBuiltTransportClient(settings, SearchGuardSSLPlugin.class).addTransportAddress(  new TransportAddress(new InetSocketAddress(elasticIpAddress, elasticPort)));**

**Comment by floragunncom** [comment]
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest
