### ISSUE TITLE
Revert "assembly removed"

### ISSUE THREAD

**Issue by azarum** [floragunncom/search-guard-ssl#94]
Hey,
would it be possible to revert https://github.com/floragunncom/search-guard-ssl/commit/a84d452363fe2fe737a511a39c568ca7a59fd51c#diff-600376dffeb79835ede4a0b285078036 ?
I currently relay on bundling the plugin through artifactory

**Comment by floragunncom** [comment]
Unfortunately no. This is the first step towards integrating the SG SSL code into the main plugin code base. ETA is with SG7.
