### ISSUE TITLE
Password needs to be encrypted while enabling TLS

### ISSUE THREAD

**Issue by esuser007** [floragunncom/search-guard-ssl#95]
Currently while creating certificates for TLS, user is asked to give one password for encrypting the privated key file, but this password can only be stored as clear-text, which may cause risk.
You may check the "searchguard.ssl.transport.pemkey_password" configuration entry for more information.
We expect it can be enhanced as encrypted format. thanks!

**Comment by floragunncom** [comment]
I guess the question is how to make elasticsearch.yml free of passwords, right? In that case, the recommendation is to use environment variable substitution:

https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html

**Comment by esuser007** [comment]
> I guess the question is how to make elasticsearch.yml free of passwords, right? In that case, the recommendation is to use environment variable substitution:
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/current/settings.html

Hi floragunncom, thank you for reply! It seems environment variables much safer but they are almost the same actually. In case some hacker log in, he is able to open config file and check the clear-text password, he is also able to use echo command to get real value from environment. We are expecting there can be some encryption mechanism for this password, or you can define one interface so that real users can define customized implementation. Please check, thanks  very much!
