### ISSUE TITLE
release 5.6.13-23 was not tagged or released

### ISSUE THREAD

**Issue by richm** [floragunncom/search-guard-ssl#96]
There is no release git tag for v5.6.13-23.  There is one for the previous 5.6 release v5.6.12-23.  There is also no v5.6.13-23 at https://github.com/floragunncom/search-guard-ssl/releases
You appear to have pushed a release v5.6.13-23 to search.maven.org without tagging/releasing at https://github.com/floragunncom/search-guard-ssl/releases

**Comment by floragunncom** [comment]
tags pushed
